[package]
name = "ctrtk"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3.25"
num_enum = { version = "0.5", default-features = false }
no_std_io = { git = "https://github.com/zaksabeast/no_std_io.git", rev = "dff97fe" }
